<b><?php echo $this->user->lang('Select which fields you wish to export and press the button to download the file'); ?>:</b><br />
<table>
    <?php foreach ( $this->fields as $field ) { ?>
    <tr>
        <td valign="top">
            <input style="margin-right:5px;" type="checkbox" name="invoices_field_<?php echo $field['fieldName']; ?>" <?php echo $field['checked']; ?> /><?php echo $field['fieldName']; ?><br />
        </td>
    </tr>
    <?php } ?>
</table><br />
<b><?php echo $this->user->lang('Invoice status'); ?>:</b>
<select name="invoice_status">
    <option value="all" selected><?php echo $this->user->lang('All invoices'); ?></option>
    <option value="unpaid"><?php echo $this->user->lang('Unpaid invoices'); ?></option>
    <option value="paid"><?php echo $this->user->lang('Paid invoices'); ?></option>
</select><br /><br />
<button class="rich-button" id="exportButton"><span><?php echo $this->user->lang("Download .csv"); ?></span></button>
