<div class="notice notice-blue">
  <div class="inside">
    <span class="bold-item"><?php echo $this->user->lang('Instructions'); ?>:</span>
    <ul>
      <li><?php echo $this->user->lang('Download the WHMCS Export tool'); ?>: <a href="../plugins/import/whmcs/gettool.php">[ <?php echo $this->user->lang('download'); ?> ]</a></li>
      <li><?php echo $this->user->lang('Upload whmcs2ce.php to your WHMCS root directory.'); ?></li>
      <li><?php echo $this->user->lang('Open the whmcs2ce.php in a web browser which will allow you to download a .csv.gz file.'); ?></li>
      <li><?php echo $this->user->lang('Delete the whmcs2ce.php from your WHMCS root directory.'); ?></li>
      <li><?php echo $this->user->lang('From this tool, select the clientexec.csv.gz file that was downloaded from the whmcs2ce.php and click import.'); ?></li>
    </ul>
  </div>
</div>

<?php if ( isset($this->error) ) { ?>
<div class="notice notice-red">
    <?php echo $this->user->lang('File upload failed.'); ?>
</div>
<?php } ?>

<?php if ( isset($this->results) ) { ?>
<div class="notice notice-yellow">
    <span class="bold-item"><?php echo $this->user->lang('Import Results'); ?>:</span>
    <ul>
        <li><?php echo $this->numAccounts; ?> <?php echo $this->user->lang('accounts added from WHMCS.'); ?></li>
        <li><?php echo $this->numPackages; ?> <?php echo $this->user->lang('packages added from WHMCS.'); ?></li>
        <li><?php echo $this->numHosting; ?> <?php echo $this->user->lang('client packages added from WHMCS.'); ?></li>
        <li><?php echo $this->numInvoices; ?> <?php echo $this->user->lang('invoices added from WHMCS.'); ?></li>
        <li><?php echo $this->numTickets; ?> <?php echo $this->user->lang('tickets added from WHMCS.'); ?></li>
    </ul>
</div>
<?php } ?>

<h6><?php echo $this->user->lang('Import WHMCS Exported File'); ?></h6>
<div><br /><?php echo $this->user->lang('Upload File'); ?>: <input type="file" name="importfile" /></div>
<br/>
<button class="rich-button" id="importButton"><span><?php echo $this->user->lang("Import"); ?></span></button>
